server:
  port: 8181
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-connections: 1000

spring:
  profiles:
    active: ${profileActive}
  application:
    name: ${project.artifactId}
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: false
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  quartz:
    scheduler-name: ${spring.application.name}-Scheduler
    auto-startup: true
    startup-delay: 1s
    # 启动时更新己存在的 Job
    overwrite-existing-jobs: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            instanceName: ${spring.application.name}-Scheduler
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX #持久化配置
            isClustered: true #打开群集功能
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties: false
            tablePrefix: QRTZ_  #数据库表前缀
            #集群中任务调度实例失效的检查时间间隔，单位为毫秒
            clusterCheckinInterval: 5000
            maxMisfiresToHandleAtATime: 1
            misfireThreshold: 60000
          threadPool: #连接池
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
    dubbo:
      enable: true
      dubbo-shutdown.enabled: true
      dubbo-configs.enabled: true
      dubbo-services.enabled: true
      dubbo-references.enabled: true
      dubbo-properties.enabled: true
  health:
    dubbo:
      status:
        defaults: memory,load
        extras: registry,load,threadpool

info:
  name: ${project.artifactId}
  description: ${project.description}
  version: ${project.version}

mybatis-plus:
  mapper-locations: classpath*:com/hdw/server/base/*/mapper/sqlMapperXml/*Mapper.xml
  type-aliases-package: com.hdw.api.base.*.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      id-type: assign_id
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: delFlag