server:
  port: 8182
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-connections: 1000

spring:
  profiles:
    active: ${profileActive}
  application:
    name: ${project.artifactId}
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: false
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
    dubbo:
      enable: true
      dubbo-shutdown.enabled: true
      dubbo-configs.enabled: true
      dubbo-services.enabled: true
      dubbo-references.enabled: true
      dubbo-properties.enabled: true
  health:
    dubbo:
      status:
        defaults: memory,load
        extras: registry,load,threadpool

info:
  name: ${project.artifactId}
  description: ${project.description}
  version: ${project.version}

mybatis-plus:
  mapper-locations: classpath*:com/hdw/server/*/mapper/sqlMapperXml/*Mapper.xml
  type-aliases-package: com.hdw.api.notice.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      id-type: assign_id
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: delFlag